/* MiniJavaParser.java */
/* Generated By:JavaCC: Do not edit this line. MiniJavaParser.java */
  package Parse;
  import java.util.LinkedList;
  public class MiniJavaParser implements MiniJavaParserConstants {

/********************/
/* MiniJava Grammar */
/********************/

// MainClass 	::= 	"class" Identifier "{" "public" "static" "void" "main" "(" "String" "[" "]" Identifier ")" "{" Statement "}" "}"
  static final public Absyn.ClassDecl MainClassDeclaration(LinkedList<Absyn.Absyn> cl) throws ParseException {Absyn.ClassDecl  cd;
 Absyn.Stmt stmt;
 Absyn.VarDecl var;
 Token name, arg;
 LinkedList<Absyn.MethodDecl> methods = new LinkedList<Absyn.MethodDecl>();
 LinkedList<Absyn.Formal> formals     = new LinkedList<Absyn.Formal>();
 LinkedList<Absyn.VarDecl> locals     = new LinkedList<Absyn.VarDecl>();
 LinkedList<Absyn.Stmt> stmts         = new LinkedList<Absyn.Stmt>();
    jj_consume_token(8);
    name = jj_consume_token(ID);
    jj_consume_token(22);
    jj_consume_token(9);
    jj_consume_token(10);
    jj_consume_token(18);
    jj_consume_token(30);
    jj_consume_token(24);
    jj_consume_token(31);
    jj_consume_token(26);
    jj_consume_token(27);
    arg = jj_consume_token(ID);
    jj_consume_token(25);
formals.add(new Absyn.Formal(
   new Absyn.ArrayType(
    new Absyn.IdentifierType("String")),
     arg.toString()));
    jj_consume_token(22);
    label_1:
    while (true) {
      if (jj_2_1(2147483647)) {
        ;
      } else {
        break label_1;
      }
      var = VarDeclaration();
locals.add(var);
    }
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 11:
      case 12:
      case 22:
      case 33:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_2;
      }
      stmt = Statement();
stmts.add(stmt);
    }
    jj_consume_token(23);
    jj_consume_token(23);
methods.add(new Absyn.MethodDecl(null, false, "main", formals,
    locals, stmts, new Absyn.IntegerLiteral(0)));
  cd = new Absyn.ClassDecl(name.toString(),
      null,
      new LinkedList<Absyn.VarDecl>(), methods);
  cl.add(cd);
  {if ("" != null) return cd;}
    throw new Error("Missing return statement in function");
}

// VarDeclaration 	::= 	Type Identifier ( = Expression )? ";"
  static final public Absyn.VarDecl VarDeclaration() throws ParseException {Absyn.Type type = null;
 Token      name = null;
 Absyn.Expr init = null;
    type = Type();
    name = jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 52:{
      jj_consume_token(52);
      init = Expression();
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      ;
    }
    jj_consume_token(28);
{if ("" != null) return new Absyn.VarDecl(type, name.toString(), init);}
    throw new Error("Missing return statement in function");
}

// Field Decleration Type <ID> ";"
  static final public Absyn.VarDecl FieldDeclaration() throws ParseException {Absyn.Type type;
 Token name;
    type = Type();
    name = jj_consume_token(ID);
    jj_consume_token(28);
{if ("" != null) return new Absyn.VarDecl(type, name.toString(), null);}
    throw new Error("Missing return statement in function");
}

// MethodDeclaration ::= "public" ("synchronized")? Type <ID> "(" (Type <ID> ("," Type <ID>)*)? ")"
//                        "{" (VarDeclaration)* (Statement)* "return" Expression ";" "}"
  static final public Absyn.MethodDecl MethodDeclaration() throws ParseException {boolean synced = false;
 Absyn.Type returnType, ptype;
 Token name, pname;
 LinkedList<Absyn.Formal> params  = new LinkedList<Absyn.Formal>();
 LinkedList<Absyn.VarDecl> locals = new LinkedList<Absyn.VarDecl>();
 LinkedList<Absyn.Stmt> stmts     = new LinkedList<Absyn.Stmt>();
 Absyn.VarDecl local;
 Absyn.Stmt stmt;
 Absyn.Expr returnVal;
    jj_consume_token(9);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 16:{
      jj_consume_token(16);
synced = true;
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    returnType = Type();
    name = jj_consume_token(ID);
    jj_consume_token(24);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 19:
    case 20:
    case ID:{
      ptype = Type();
      pname = jj_consume_token(ID);
params.add(new Absyn.Formal(ptype, pname.toString()));
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 29:{
          ;
          break;
          }
        default:
          jj_la1[3] = jj_gen;
          break label_3;
        }
        jj_consume_token(29);
        ptype = Type();
        pname = jj_consume_token(ID);
params.add(new Absyn.Formal(ptype, pname.toString()));
      }
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      ;
    }
    jj_consume_token(25);
    jj_consume_token(22);
    label_4:
    while (true) {
      if (jj_2_2(2147483647)) {
        ;
      } else {
        break label_4;
      }
      local = VarDeclaration();
locals.add(local);
    }
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 11:
      case 12:
      case 22:
      case 33:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        break label_5;
      }
      stmt = Statement();
stmts.add(stmt);
    }
    jj_consume_token(17);
    returnVal = Expression();
    jj_consume_token(28);
    jj_consume_token(23);
{if ("" != null) return new Absyn.MethodDecl(returnType, synced, name.toString(), params, locals, stmts, returnVal);}
    throw new Error("Missing return statement in function");
}

// VoidDeclaration ::= "public" "void" <ID> "(" ")" "{" (VarDeclaration)* (Statement)* "}"
  static final public Absyn.VoidDecl VoidDeclaration() throws ParseException {Token name;
 LinkedList<Absyn.VarDecl> locals = new LinkedList<Absyn.VarDecl>();
 LinkedList<Absyn.Stmt> stmts     = new LinkedList<Absyn.Stmt>();
 Absyn.VarDecl local;
 Absyn.Stmt stmt;
    jj_consume_token(9);
    jj_consume_token(18);
    name = jj_consume_token(ID);
    jj_consume_token(24);
    jj_consume_token(25);
    jj_consume_token(22);
    label_6:
    while (true) {
      if (jj_2_3(2147483647)) {
        ;
      } else {
        break label_6;
      }
      local = VarDeclaration();
locals.add(local);
    }
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 11:
      case 12:
      case 22:
      case 33:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        break label_7;
      }
      stmt = Statement();
stmts.add(stmt);
    }
    jj_consume_token(23);
{if ("" != null) return new Absyn.VoidDecl(name.toString(), locals, stmts);}
    throw new Error("Missing return statement in function");
}

// ClassDeclaration  ::= "class" <ID> ( "extends" <ID> )? "{" ( FieldDeclaration | MethodDeclaration )* "}"
// ThreadDeclaration ::= "class" <ID> "extends" "Thread" "{" ( FieldDeclaration | MethodDeclaration | VoidDeclaration )* "}"
  static final public Absyn.Absyn ClassOrThreadDeclaration() throws ParseException {Token name, parentId = null;
 LinkedList<Absyn.VarDecl> fields       = new LinkedList<Absyn.VarDecl>();
 LinkedList<Absyn.MethodDecl> methods   = new LinkedList<Absyn.MethodDecl>();
 LinkedList<Absyn.VoidDecl> voidMethods = new LinkedList<Absyn.VoidDecl>();
 Absyn.VarDecl field;
 Absyn.MethodDecl method;
 Absyn.VoidDecl vmethod;
    jj_consume_token(8);
    name = jj_consume_token(ID);
    if (jj_2_5(2147483647)) {
      jj_consume_token(37);
      jj_consume_token(32);
      jj_consume_token(22);
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 9:
        case 19:
        case 20:
        case ID:{
          ;
          break;
          }
        default:
          jj_la1[7] = jj_gen;
          break label_8;
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 19:
        case 20:
        case ID:{
          field = FieldDeclaration();
fields.add(field);
          break;
          }
        default:
          jj_la1[8] = jj_gen;
          if (jj_2_4(2)) {
            vmethod = VoidDeclaration();
voidMethods.add(vmethod);
          } else {
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case 9:{
              method = MethodDeclaration();
methods.add(method);
              break;
              }
            default:
              jj_la1[9] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
          }
        }
      }
      jj_consume_token(23);
{if ("" != null) return new Absyn.ThreadDecl(name.toString(), fields, methods, voidMethods);}
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 22:
      case 37:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 37:{
          jj_consume_token(37);
          parentId = jj_consume_token(ID);
          break;
          }
        default:
          jj_la1[10] = jj_gen;
          ;
        }
        jj_consume_token(22);
        label_9:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case 9:
          case 19:
          case 20:
          case ID:{
            ;
            break;
            }
          default:
            jj_la1[11] = jj_gen;
            break label_9;
          }
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case 19:
          case 20:
          case ID:{
            field = FieldDeclaration();
fields.add(field);
            break;
            }
          case 9:{
            method = MethodDeclaration();
methods.add(method);
            break;
            }
          default:
            jj_la1[12] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
        jj_consume_token(23);
{if ("" != null) return new Absyn.ClassDecl(name.toString(),
               (parentId == null ? null : parentId.toString()), fields, methods);}
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
}

// Goal         ::=     MainClass ( ClassDeclaration | ThreadDeclaration )* <EOF>
  static final public Absyn.Program Goal() throws ParseException {LinkedList<Absyn.Absyn> cl = new LinkedList<Absyn.Absyn>();
        Absyn.Absyn decl;
    MainClassDeclaration(cl);
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 8:{
        ;
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        break label_10;
      }
      decl = ClassOrThreadDeclaration();
cl.add(decl);
    }
    jj_consume_token(0);
{if ("" != null) return new Absyn.Program(cl);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Type Type() throws ParseException {Absyn.Type type;
    type = BaseType();
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 26:{
        ;
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        break label_11;
      }
      jj_consume_token(26);
      jj_consume_token(27);
type = new Absyn.ArrayType(type);
    }
{if ("" != null) return type;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Type BaseType() throws ParseException {Token name;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 19:{
      jj_consume_token(19);
{if ("" != null) return new Absyn.IntegerType();}
      break;
      }
    case 20:{
      jj_consume_token(20);
{if ("" != null) return new Absyn.BooleanType();}
      break;
      }
    case ID:{
      name = jj_consume_token(ID);
{if ("" != null) return new Absyn.IdentifierType(name.toString());}
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Stmt Statement() throws ParseException {Absyn.Stmt stmt;
 Absyn.AssignableExpr lhs;
 Absyn.Expr rhs;
 LinkedList <Absyn.Stmt> stmts = new LinkedList <Absyn.Stmt>();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 22:{
      jj_consume_token(22);
      label_12:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 11:
        case 12:
        case 22:
        case 33:
        case ID:{
          ;
          break;
          }
        default:
          jj_la1[17] = jj_gen;
          break label_12;
        }
        stmt = Statement();
stmts.add(stmt);
      }
      jj_consume_token(23);
{if ("" != null) return new Absyn.BlockStmt(stmts);}
      break;
      }
    case 33:{
      stmt = XinuCallStatement();
{if ("" != null) return stmt;}
      break;
      }
    case 11:{
      stmt = IfState();
{if ("" != null) return stmt;}
      break;
      }
    case 12:{
      stmt = WhileState();
{if ("" != null) return stmt;}
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      if (jj_2_6(2147483647)) {
        lhs = AssignableExpr();
        jj_consume_token(52);
        rhs = Expression();
        jj_consume_token(28);
{if ("" != null) return new Absyn.AssignStmt(lhs, rhs);}
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
}

  static final public Absyn.XinuCallStmt XinuCallStatement() throws ParseException {Token method;
 Absyn.Expr arg;
 LinkedList<Absyn.Expr> args = new LinkedList<Absyn.Expr>();
    jj_consume_token(33);
    jj_consume_token(21);
    method = jj_consume_token(ID);
    jj_consume_token(24);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 14:
    case 15:
    case 24:
    case 33:
    case 34:
    case 35:
    case 36:
    case INT:
    case STRING:
    case 41:
    case 50:
    case ID:{
      arg = Expression();
args.add(arg);
      label_13:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 29:{
          ;
          break;
          }
        default:
          jj_la1[19] = jj_gen;
          break label_13;
        }
        jj_consume_token(29);
        arg = Expression();
args.add(arg);
      }
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      ;
    }
    jj_consume_token(25);
    jj_consume_token(28);
{if ("" != null) return new Absyn.XinuCallStmt(method.toString(), args);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.AssignableExpr AssignableExpr() throws ParseException {Absyn.Expr e, arg;
 Token t, id;
    t = jj_consume_token(ID);
Absyn.Expr result = new Absyn.IdentifierExpr(t.toString());
    label_14:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 21:
      case 26:{
        ;
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        break label_14;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 21:{
        jj_consume_token(21);
        id = jj_consume_token(ID);
result = new Absyn.FieldExpr(result, id.toString());
        break;
        }
      case 26:{
        jj_consume_token(26);
        arg = Expression();
        jj_consume_token(27);
result = new Absyn.ArrayExpr(result, arg);
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return (Absyn.AssignableExpr) result;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr Expression() throws ParseException {Absyn.Expr e;
    e = Or();
{if ("" != null) return e;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr Or() throws ParseException {Absyn.Expr left, right;
    left = And();
    label_15:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 49:{
        ;
        break;
        }
      default:
        jj_la1[23] = jj_gen;
        break label_15;
      }
      jj_consume_token(49);
      right = And();
left = new Absyn.OrExpr(left,right);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr And() throws ParseException {Absyn.Expr left, right;
    left = Equals();
    label_16:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 48:{
        ;
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        break label_16;
      }
      jj_consume_token(48);
      right = Equals();
left = new Absyn.AndExpr(left,right);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr Equals() throws ParseException {Absyn.Expr left, right;
    left = Compare();
    label_17:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 46:
      case 47:{
        ;
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        break label_17;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 46:{
        jj_consume_token(46);
        right = Compare();
left = new Absyn.EqualExpr(left,right);
        break;
        }
      case 47:{
        jj_consume_token(47);
        right = Compare();
left = new Absyn.NotEqExpr(left,right);
        break;
        }
      default:
        jj_la1[26] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr Compare() throws ParseException {Absyn.Expr left, right;
    left = AddSub();
    label_18:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 44:
      case 45:{
        ;
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        break label_18;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 45:{
        jj_consume_token(45);
        right = AddSub();
left = new Absyn.GreaterExpr(left,right);
        break;
        }
      case 44:{
        jj_consume_token(44);
        right = AddSub();
left = new Absyn.LesserExpr(left,right);
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr AddSub() throws ParseException {Absyn.Expr left, right;
    left = MultDiv();
    label_19:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 40:
      case 41:{
        ;
        break;
        }
      default:
        jj_la1[29] = jj_gen;
        break label_19;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 40:{
        jj_consume_token(40);
        right = MultDiv();
left = new Absyn.AddExpr(left,right);
        break;
        }
      case 41:{
        jj_consume_token(41);
        right = MultDiv();
left = new Absyn.SubExpr(left,right);
        break;
        }
      default:
        jj_la1[30] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr MultDiv() throws ParseException {Absyn.Expr left, right;
    left = Unary();
    label_20:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 42:
      case 43:{
        ;
        break;
        }
      default:
        jj_la1[31] = jj_gen;
        break label_20;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 42:{
        jj_consume_token(42);
        right = Unary();
left = new Absyn.MulExpr(left,right);
        break;
        }
      case 43:{
        jj_consume_token(43);
        right = Unary();
left = new Absyn.DivExpr(left,right);
        break;
        }
      default:
        jj_la1[32] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr Unary() throws ParseException {Absyn.Expr e;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 41:{
      jj_consume_token(41);
      e = Unary();
{if ("" != null) return new Absyn.NegExpr(e);}
      break;
      }
    case 50:{
      jj_consume_token(50);
      e = Unary();
{if ("" != null) return new Absyn.NotExpr(e);}
      break;
      }
    case 14:
    case 15:
    case 24:
    case 33:
    case 34:
    case 35:
    case 36:
    case INT:
    case STRING:
    case ID:{
      e = Postfix();
{if ("" != null) return e;}
      break;
      }
    default:
      jj_la1[33] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr Postfix() throws ParseException {Absyn.Expr e, arg;
 Token id;
 LinkedList<Absyn.Expr> args;
    e = Prime();
    label_21:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 21:
      case 26:{
        ;
        break;
        }
      default:
        jj_la1[34] = jj_gen;
        break label_21;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 21:{
        jj_consume_token(21);
        id = jj_consume_token(ID);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 24:{
          jj_consume_token(24);
args = new LinkedList<Absyn.Expr>();
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case 14:
          case 15:
          case 24:
          case 33:
          case 34:
          case 35:
          case 36:
          case INT:
          case STRING:
          case 41:
          case 50:
          case ID:{
            arg = Expression();
args.add(arg);
            label_22:
            while (true) {
              switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
              case 29:{
                ;
                break;
                }
              default:
                jj_la1[35] = jj_gen;
                break label_22;
              }
              jj_consume_token(29);
              arg = Expression();
args.add(arg);
            }
            break;
            }
          default:
            jj_la1[36] = jj_gen;
            ;
          }
          jj_consume_token(25);
e = new Absyn.CallExpr(e, id.toString(), args);
          break;
          }
        default:
          jj_la1[37] = jj_gen;
e = new Absyn.FieldExpr(e, id.toString());
        }
        break;
        }
      case 26:{
        jj_consume_token(26);
        arg = Expression();
        jj_consume_token(27);
e = new Absyn.ArrayExpr(e, arg);
        break;
        }
      default:
        jj_la1[38] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return e;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr Prime() throws ParseException {Token t; Absyn.Expr e, arg; Absyn.Type type; LinkedList<Absyn.Expr> args = new LinkedList<Absyn.Expr>();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STRING:{
      t = jj_consume_token(STRING);
{if ("" != null) return new Absyn.StringLiteral(t.toString());}
      break;
      }
    case INT:{
      t = jj_consume_token(INT);
{if ("" != null) return new Absyn.IntegerLiteral(Integer.parseInt(t.image));}
      break;
      }
    case 36:{
      jj_consume_token(36);
{if ("" != null) return new Absyn.NullExpr();}
      break;
      }
    default:
      jj_la1[41] = jj_gen;
      if (jj_2_8(3)) {
        jj_consume_token(34);
        t = jj_consume_token(ID);
        jj_consume_token(24);
        jj_consume_token(25);
{if ("" != null) return new Absyn.NewObjectExpr(t.toString());}
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 34:{
          jj_consume_token(34);
          type = BaseType();
          jj_consume_token(26);
          e = Expression();
          jj_consume_token(27);
LinkedList<Absyn.Expr> sizes = new LinkedList<Absyn.Expr>(); sizes.add(e);
          label_23:
          while (true) {
            if (jj_2_7(2)) {
              ;
            } else {
              break label_23;
            }
            jj_consume_token(26);
            jj_consume_token(27);
sizes.add(null);
          }
{if ("" != null) return new Absyn.NewArrayExpr(type, sizes);}
          break;
          }
        case 33:{
          jj_consume_token(33);
          jj_consume_token(21);
          t = jj_consume_token(ID);
          jj_consume_token(24);
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case 14:
          case 15:
          case 24:
          case 33:
          case 34:
          case 35:
          case 36:
          case INT:
          case STRING:
          case 41:
          case 50:
          case ID:{
            arg = Expression();
args.add(arg);
            label_24:
            while (true) {
              switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
              case 29:{
                ;
                break;
                }
              default:
                jj_la1[39] = jj_gen;
                break label_24;
              }
              jj_consume_token(29);
              arg = Expression();
args.add(arg);
            }
            break;
            }
          default:
            jj_la1[40] = jj_gen;
            ;
          }
          jj_consume_token(25);
{if ("" != null) return new Absyn.XinuCallExpr(t.toString(), args);}
          break;
          }
        case 14:{
          jj_consume_token(14);
{if ("" != null) return new Absyn.TrueExpr();}
          break;
          }
        case 15:{
          jj_consume_token(15);
{if ("" != null) return new Absyn.FalseExpr();}
          break;
          }
        case 35:{
          jj_consume_token(35);
{if ("" != null) return new Absyn.ThisExpr();}
          break;
          }
        case ID:{
          t = jj_consume_token(ID);
{if ("" != null) return new Absyn.IdentifierExpr(t.toString());}
          break;
          }
        case 24:{
          jj_consume_token(24);
          e = Expression();
          jj_consume_token(25);
{if ("" != null) return e;}
          break;
          }
        default:
          jj_la1[42] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Stmt IfState() throws ParseException {Absyn.Expr condition;
 Absyn.Stmt then;
 Absyn.Stmt elseStmt = null;
    jj_consume_token(11);
    jj_consume_token(24);
    condition = Expression();
    jj_consume_token(25);
    then = Statement();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 13:{
      jj_consume_token(13);
      elseStmt = Statement();
      break;
      }
    default:
      jj_la1[43] = jj_gen;
      ;
    }
{if ("" != null) return new Absyn.IfStmt(condition ,then,elseStmt);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Stmt WhileState() throws ParseException {Absyn.Expr condition;
 Absyn.Stmt then;
    jj_consume_token(12);
    jj_consume_token(24);
    condition = Expression();
    jj_consume_token(25);
    then = Statement();
{if ("" != null) return new Absyn.WhileStmt(condition, then);}
    throw new Error("Missing return statement in function");
}

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_7()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_8()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_3R_And_367_12_43()
 {
    if (jj_scan_token(48)) return true;
    if (jj_3R_Equals_375_85_42()) return true;
    return false;
  }

  static private boolean jj_3R_Prime_456_15_78()
 {
    if (jj_3R_Expression_350_9_33()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Prime_457_19_81()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_Compare_385_85_44()
 {
    if (jj_3R_AddSub_395_85_46()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Compare_386_11_47()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_Prime_463_4_75()
 {
    if (jj_scan_token(24)) return true;
    if (jj_3R_Expression_350_9_33()) return true;
    if (jj_scan_token(25)) return true;
    return false;
  }

  static private boolean jj_3R_Prime_462_4_74()
 {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3R_VarDeclaration_179_2_25()
 {
    if (jj_3R_Type_288_2_28()) return true;
    if (jj_scan_token(ID)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_VarDeclaration_179_30_29()) jj_scanpos = xsp;
    if (jj_scan_token(28)) return true;
    return false;
  }

  static private boolean jj_3R_Prime_461_4_73()
 {
    if (jj_scan_token(35)) return true;
    return false;
  }

  static private boolean jj_3R_Prime_460_4_72()
 {
    if (jj_scan_token(15)) return true;
    return false;
  }

  static private boolean jj_3R_Prime_459_4_71()
 {
    if (jj_scan_token(14)) return true;
    return false;
  }

  static private boolean jj_3_7()
 {
    if (jj_scan_token(26)) return true;
    if (jj_scan_token(27)) return true;
    return false;
  }

  static private boolean jj_3R_Equals_375_85_42()
 {
    if (jj_3R_Compare_385_85_44()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Equals_376_11_45()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_Prime_455_4_70()
 {
    if (jj_scan_token(33)) return true;
    if (jj_scan_token(21)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(24)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Prime_456_15_78()) jj_scanpos = xsp;
    if (jj_scan_token(25)) return true;
    return false;
  }

  static private boolean jj_3_5()
 {
    if (jj_scan_token(37)) return true;
    if (jj_scan_token(32)) return true;
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_VarDeclaration_179_2_25()) return true;
    return false;
  }

  static private boolean jj_3R_Or_358_4_41()
 {
    if (jj_scan_token(49)) return true;
    if (jj_3R_And_366_85_40()) return true;
    return false;
  }

  static private boolean jj_3R_Prime_451_4_69()
 {
    if (jj_scan_token(34)) return true;
    if (jj_3R_BaseType_298_4_31()) return true;
    if (jj_scan_token(26)) return true;
    if (jj_3R_Expression_350_9_33()) return true;
    if (jj_scan_token(27)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_7()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_4()
 {
    if (jj_3R_VoidDeclaration_230_2_26()) return true;
    return false;
  }

  static private boolean jj_3R_Expression_350_9_33()
 {
    if (jj_3R_Or_357_85_39()) return true;
    return false;
  }

  static private boolean jj_3_8()
 {
    if (jj_scan_token(34)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(24)) return true;
    if (jj_scan_token(25)) return true;
    return false;
  }

  static private boolean jj_3R_Prime_449_4_68()
 {
    if (jj_scan_token(36)) return true;
    return false;
  }

  static private boolean jj_3R_Prime_448_4_67()
 {
    if (jj_scan_token(INT)) return true;
    return false;
  }

  static private boolean jj_3R_And_366_85_40()
 {
    if (jj_3R_Equals_375_85_42()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_And_367_12_43()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_Postfix_432_18_83()
 {
    if (jj_scan_token(29)) return true;
    if (jj_3R_Expression_350_9_33()) return true;
    return false;
  }

  static private boolean jj_3R_Prime_447_2_66()
 {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  static private boolean jj_3R_Prime_447_2_64()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Prime_447_2_66()) {
    jj_scanpos = xsp;
    if (jj_3R_Prime_448_4_67()) {
    jj_scanpos = xsp;
    if (jj_3R_Prime_449_4_68()) {
    jj_scanpos = xsp;
    if (jj_3_8()) {
    jj_scanpos = xsp;
    if (jj_3R_Prime_451_4_69()) {
    jj_scanpos = xsp;
    if (jj_3R_Prime_455_4_70()) {
    jj_scanpos = xsp;
    if (jj_3R_Prime_459_4_71()) {
    jj_scanpos = xsp;
    if (jj_3R_Prime_460_4_72()) {
    jj_scanpos = xsp;
    if (jj_3R_Prime_461_4_73()) {
    jj_scanpos = xsp;
    if (jj_3R_Prime_462_4_74()) {
    jj_scanpos = xsp;
    if (jj_3R_Prime_463_4_75()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_Postfix_431_14_82()
 {
    if (jj_3R_Expression_350_9_33()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Postfix_432_18_83()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_Postfix_435_10_80()
 {
    return false;
  }

  static private boolean jj_3R_AssignableExpr_341_8_35()
 {
    if (jj_scan_token(26)) return true;
    if (jj_3R_Expression_350_9_33()) return true;
    if (jj_scan_token(27)) return true;
    return false;
  }

  static private boolean jj_3R_Postfix_437_6_77()
 {
    if (jj_scan_token(26)) return true;
    if (jj_3R_Expression_350_9_33()) return true;
    if (jj_scan_token(27)) return true;
    return false;
  }

  static private boolean jj_3R_AssignableExpr_340_8_30()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_AssignableExpr_340_8_34()) {
    jj_scanpos = xsp;
    if (jj_3R_AssignableExpr_341_8_35()) return true;
    }
    return false;
  }

  static private boolean jj_3R_AssignableExpr_340_8_34()
 {
    if (jj_scan_token(21)) return true;
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3R_Or_357_85_39()
 {
    if (jj_3R_And_366_85_40()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Or_358_4_41()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_Postfix_430_10_79()
 {
    if (jj_scan_token(24)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Postfix_431_14_82()) jj_scanpos = xsp;
    if (jj_scan_token(25)) return true;
    return false;
  }

  static private boolean jj_3_3()
 {
    if (jj_3R_VarDeclaration_179_2_25()) return true;
    return false;
  }

  static private boolean jj_3R_AssignableExpr_337_4_27()
 {
    if (jj_scan_token(ID)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_AssignableExpr_340_8_30()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_Postfix_428_6_76()
 {
    if (jj_scan_token(21)) return true;
    if (jj_scan_token(ID)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Postfix_430_10_79()) {
    jj_scanpos = xsp;
    if (jj_3R_Postfix_435_10_80()) return true;
    }
    return false;
  }

  static private boolean jj_3R_Postfix_428_6_65()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Postfix_428_6_76()) {
    jj_scanpos = xsp;
    if (jj_3R_Postfix_437_6_77()) return true;
    }
    return false;
  }

  static private boolean jj_3R_Postfix_426_2_63()
 {
    if (jj_3R_Prime_447_2_64()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Postfix_428_6_65()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_Unary_417_11_60()
 {
    if (jj_3R_Postfix_426_2_63()) return true;
    return false;
  }

  static private boolean jj_3R_Unary_416_11_59()
 {
    if (jj_scan_token(50)) return true;
    if (jj_3R_Unary_415_10_54()) return true;
    return false;
  }

  static private boolean jj_3R_Unary_415_10_58()
 {
    if (jj_scan_token(41)) return true;
    if (jj_3R_Unary_415_10_54()) return true;
    return false;
  }

  static private boolean jj_3R_Unary_415_10_54()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Unary_415_10_58()) {
    jj_scanpos = xsp;
    if (jj_3R_Unary_416_11_59()) {
    jj_scanpos = xsp;
    if (jj_3R_Unary_417_11_60()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3_6()
 {
    if (jj_3R_AssignableExpr_337_4_27()) return true;
    if (jj_scan_token(52)) return true;
    return false;
  }

  static private boolean jj_3R_VoidDeclaration_230_2_26()
 {
    if (jj_scan_token(9)) return true;
    if (jj_scan_token(18)) return true;
    return false;
  }

  static private boolean jj_3R_MultDiv_407_11_62()
 {
    if (jj_scan_token(43)) return true;
    if (jj_3R_Unary_415_10_54()) return true;
    return false;
  }

  static private boolean jj_3_2()
 {
    if (jj_3R_VarDeclaration_179_2_25()) return true;
    return false;
  }

  static private boolean jj_3R_MultDiv_406_11_61()
 {
    if (jj_scan_token(42)) return true;
    if (jj_3R_Unary_415_10_54()) return true;
    return false;
  }

  static private boolean jj_3R_MultDiv_406_11_55()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_MultDiv_406_11_61()) {
    jj_scanpos = xsp;
    if (jj_3R_MultDiv_407_11_62()) return true;
    }
    return false;
  }

  static private boolean jj_3R_AddSub_397_11_57()
 {
    if (jj_scan_token(41)) return true;
    if (jj_3R_MultDiv_405_85_50()) return true;
    return false;
  }

  static private boolean jj_3R_AddSub_396_11_56()
 {
    if (jj_scan_token(40)) return true;
    if (jj_3R_MultDiv_405_85_50()) return true;
    return false;
  }

  static private boolean jj_3R_AddSub_396_11_51()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_AddSub_396_11_56()) {
    jj_scanpos = xsp;
    if (jj_3R_AddSub_397_11_57()) return true;
    }
    return false;
  }

  static private boolean jj_3R_VarDeclaration_179_30_29()
 {
    if (jj_scan_token(52)) return true;
    if (jj_3R_Expression_350_9_33()) return true;
    return false;
  }

  static private boolean jj_3R_BaseType_300_4_38()
 {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3R_Compare_387_11_53()
 {
    if (jj_scan_token(44)) return true;
    if (jj_3R_AddSub_395_85_46()) return true;
    return false;
  }

  static private boolean jj_3R_BaseType_299_4_37()
 {
    if (jj_scan_token(20)) return true;
    return false;
  }

  static private boolean jj_3R_Compare_386_11_52()
 {
    if (jj_scan_token(45)) return true;
    if (jj_3R_AddSub_395_85_46()) return true;
    return false;
  }

  static private boolean jj_3R_BaseType_298_4_31()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_BaseType_298_4_36()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseType_299_4_37()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseType_300_4_38()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_BaseType_298_4_36()
 {
    if (jj_scan_token(19)) return true;
    return false;
  }

  static private boolean jj_3R_Compare_386_11_47()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Compare_386_11_52()) {
    jj_scanpos = xsp;
    if (jj_3R_Compare_387_11_53()) return true;
    }
    return false;
  }

  static private boolean jj_3R_MultDiv_405_85_50()
 {
    if (jj_3R_Unary_415_10_54()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_MultDiv_406_11_55()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_Type_289_4_32()
 {
    if (jj_scan_token(26)) return true;
    if (jj_scan_token(27)) return true;
    return false;
  }

  static private boolean jj_3R_Equals_376_11_45()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Equals_376_11_48()) {
    jj_scanpos = xsp;
    if (jj_3R_Equals_377_4_49()) return true;
    }
    return false;
  }

  static private boolean jj_3R_Equals_376_11_48()
 {
    if (jj_scan_token(46)) return true;
    if (jj_3R_Compare_385_85_44()) return true;
    return false;
  }

  static private boolean jj_3R_Type_288_2_28()
 {
    if (jj_3R_BaseType_298_4_31()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Type_289_4_32()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_AddSub_395_85_46()
 {
    if (jj_3R_MultDiv_405_85_50()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_AddSub_396_11_51()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_Prime_457_19_81()
 {
    if (jj_scan_token(29)) return true;
    if (jj_3R_Expression_350_9_33()) return true;
    return false;
  }

  static private boolean jj_3R_Equals_377_4_49()
 {
    if (jj_scan_token(47)) return true;
    if (jj_3R_Compare_385_85_44()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public MiniJavaParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[44];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x401800,0x0,0x10000,0x20000000,0x180000,0x401800,0x401800,0x180200,0x180000,0x200,0x0,0x180200,0x180200,0x400000,0x100,0x4000000,0x180000,0x401800,0x401800,0x20000000,0x100c000,0x4200000,0x4200000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x100c000,0x4200000,0x20000000,0x100c000,0x1000000,0x4200000,0x20000000,0x100c000,0x0,0x100c000,0x2000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x200002,0x100000,0x0,0x0,0x200000,0x200002,0x200002,0x200000,0x200000,0x0,0x20,0x200000,0x200000,0x20,0x0,0x0,0x200000,0x200002,0x2,0x0,0x2402de,0x0,0x0,0x20000,0x10000,0xc000,0xc000,0x3000,0x3000,0x300,0x300,0xc00,0xc00,0x2402de,0x0,0x0,0x2402de,0x0,0x0,0x0,0x2402de,0xd0,0x20000e,0x0,};
	}
  static final private JJCalls[] jj_2_rtns = new JJCalls[8];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MiniJavaParser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MiniJavaParser(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 44; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 44; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MiniJavaParser(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 44; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 44; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MiniJavaParser(MiniJavaParserTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 44; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MiniJavaParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 44; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[58];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 44; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 58; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 8; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			   case 6: jj_3_7(); break;
			   case 7: jj_3_8(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

                               }
