/* Copyright (C) 2007, 2013, Marquette University.  All rights reserved. */
/* 2013 Jan 30 : Includes Xinu.* external calls and Concurrency syntax.  */
 /**
  2  * COSC 4400 - Project #3
  3  * 
  4  * @authors Luke Sam 
  5  * Instructor Dr. Brylow
  6  * TA-BOT:MAILTO luke.sharba@marquette.edu 
  7  * TA-BOT:MAILTO samuel.biskupic@marquette.edu
  8  */

PARSER_BEGIN(MiniJavaParser)
  package Parse;
  import java.util.LinkedList;
  public class MiniJavaParser {}
PARSER_END(MiniJavaParser)

TOKEN_MGR_DECLS :
{
    static boolean anyErrors = false;
    static void error(String msg)
	{
        	anyErrors = true;
        	System.err.println(msg + ": line " + input_stream.getEndLine()
                           + ", column " + input_stream.getEndColumn());
    	}
}

/****************/
/* White space. */
/****************/
SKIP :
{
	  " " | "\t" | "\n" | "\r" | "\f"
}

/*************************/
/* Lexical Specification */
/*************************/

TOKEN :
{

	/* Reserved words. */
	  < "class" >
	| < "public" >
	| < "static" >
	| < "if" >
	| < "while" >
	| < "else" >
	| < "true" >
	| < "false" >

	/* Types. */
	| < "void" >
	| < "int" >
	| < "boolean" >

	/* Operators. */
	| < "." >

	/* Grouping tokens. */
	| < "{" >
	| < "}" >
	| < "(" >
	| < ")" >
	| < "[" >
	| < "]" >
	| < ";" >
	| < "," >

	/* Reserved words that aren't really reserved in Java. */
	| < "main" >
	| < "String" > 
	| < "Thread" > 
	| < "Xinu" >
	| < "new" >
	| < "this" >
	| < "null" >
	| < "extends" >
}


/************/
/* Literals */
/************/

TOKEN :
{
	  < INT: ( "0" | ["1"-"9"] (["0"-"9"])* ) >
	| < STRING: "\"" (~["\""])*  "\"" >
}

/***************/
/*  Operators  */
/***************/
TOKEN:
{
	< "+" > | < "-" > | < "*" > | < "/" >
	| < "<" > | < ">" > | < "==" > | < "!=" >
	| < "&&" > | < "||" > | < "!" > | < "?" > | < "=" >
}


/***************/
/* Identifiers */
/***************/
TOKEN :
{
	  < ID: <LETTER> (<LETTER>|<DIGIT>|<UNDER>)* >
	| < #LETTER: ["A"-"Z","a"-"z"] >
	| < #DIGIT: ["0"-"9"] >
	| < #UNDER: "_" >
}

<DEFAULT>
SKIP :
{
  <~[]> { error("Illegal token"); }
}

/********************/
/* MiniJava Grammar */
/********************/

// Goal 	::= 	MainClass ( ClassDeclaration | ThreadDeclaration )* <EOF>
Absyn.Program Goal() :
{
	LinkedList<Absyn.ClassDecl> cl = new LinkedList<Absyn.ClassDecl>();
}
{
	MainClassDeclaration(cl) <EOF>
	{ return new Absyn.Program(cl); }
}

// MainClass 	::= 	"class" Identifier "{" "public" "static" "void" "main" "(" "String" "[" "]" Identifier ")" "{" Statement "}" "}"
Absyn.ClassDecl MainClassDeclaration(LinkedList<Absyn.ClassDecl> cl) :
{
	Absyn.ClassDecl  cd;
	Absyn.Stmt stmt;
	Absyn.VarDecl var;
	Token name, arg;
	LinkedList<Absyn.MethodDecl> methods = new LinkedList<Absyn.MethodDecl>();
	LinkedList<Absyn.Formal> formals     = new LinkedList<Absyn.Formal>();
	LinkedList<Absyn.VarDecl> locals     = new LinkedList<Absyn.VarDecl>();
	LinkedList<Absyn.Stmt> stmts         = new LinkedList<Absyn.Stmt>();
}
{
  "class" name = <ID> "{" "public" "static" "void" "main"
	"(" "String" "[" "]" arg = <ID> ")"
	{ formals.add(new Absyn.Formal(
			new Absyn.ArrayType(	
				new Absyn.IdentifierType("String")),
					arg.toString())); }
	"{" (LOOKAHEAD(VarDeclaration()) var = VarDeclaration()
		{ locals.add(var); } )*
	(stmt = Statement() { stmts.add(stmt); } )*
	"}" "}"

	{
		methods.add(new Absyn.MethodDecl(null, false, "main", formals,
				locals, stmts, new Absyn.IntegerLiteral(0)));
		cd = new Absyn.ClassDecl(name.toString(),
						null,
						new LinkedList<Absyn.VarDecl>(), methods);
		cl.add(cd);
		return cd;
	}
}

// VarDeclaration 	::= 	Type Identifier ( = Expression )? ";"
Absyn.VarDecl VarDeclaration() :
{
	Absyn.Type type = null;
	Token      name = null;
	Absyn.Expr init = null;
}
{
	type = Type() name = <ID> [ "=" init = Expression() ] ";"
	{ return new Absyn.VarDecl(type, name.toString(), init); }
}

Absyn.Type Type() :
{
	Absyn.Type type;
}
{
	type = BaseType()
	( "[" "]" { type = new Absyn.ArrayType(type); } )*
	{ return type; }
}

Absyn.Type BaseType() :
{
	Token name;
}
{
	  "int"		{ return new Absyn.IntegerType();} //base applies [] so arrays will work
	| "boolean"	{ return new Absyn.BooleanType();}
	| name = <ID>	{ return new Absyn.IdentifierType(name.toString());} 
}


Absyn.Stmt Statement() :
{
	Absyn.Stmt stmt;
}
{	
	stmt = XinuCallStatement()	{ return stmt; }
	| stmt = IfState()	{return stmt; }
	| stmt = WhileState()      {return stmt; }
}

Absyn.XinuCallStmt XinuCallStatement() :
{
	Token method;
	Absyn.Expr arg;
	LinkedList<Absyn.Expr> args = new LinkedList<Absyn.Expr>();
}
{
	"Xinu" "." method = <ID> 
	"(" [ arg = Expression() { args.add(arg); }
		( "," arg = Expression()  { args.add(arg); } )* ]
	")" ";" { return new Absyn.XinuCallStmt(method.toString(), args); }
}

Absyn.Expr Expression() :  //Loosest to tightest
{
	Absyn.Expr e;
}
{
        e = Or()
	{return e;}
}
Absyn.Expr Or() :
{
    Absyn.Expr left, right;
}
{                                                                                   left = And()
	( "||" right = And() {left = new Absyn.OrExpr(left,right);} )*
	{return left;}
}

 Absyn.Expr And() :
{
    Absyn.Expr left, right;
}
{                                                                                   left = Equals()
         ( "&&" right = Equals() {left = new Absyn.AndExpr(left,right);} )*
         {return left;}
}

 Absyn.Expr Equals() :
{
    Absyn.Expr left, right;
}
{                                                                                   left = Compare()
        ( "==" right = Compare() {left = new Absyn.EqualExpr(left,right);} 
	| "!=" right = Compare() {left = new Absyn.NotEqExpr(left,right);})*
        {return left;}
}

Absyn.Expr Compare() :
{
    Absyn.Expr left, right;
}
{                                                                                   left = AddSub()
        ( ">" right = AddSub() {left = new Absyn.GreaterExpr(left,right);}
        | "<" right = AddSub() {left = new Absyn.LesserExpr(left,right);})*
        {return left;}
}

Absyn.Expr AddSub() :
{
    Absyn.Expr left, right;
}
{                                                                                   left = MultDiv()
        ( "+" right = MultDiv() {left = new Absyn.AddExpr(left,right);}
        | "-" right = MultDiv() {left = new Absyn.SubExpr(left,right);})*
        {return left;}
}

Absyn.Expr MultDiv() :
{
    Absyn.Expr left, right;
}
{                                                                                   left = Unary()
        ( "*" right = Unary() {left = new Absyn.MulExpr(left,right);}
        | "/" right = Unary() {left = new Absyn.DivExpr(left,right);})*
        {return left;}
}
Absyn.Expr Unary() :
{
	Absyn.Expr e;
}
{
         "-" right = Prime() {return new Absyn.NegExpr(e);}
        | "!" right = Prime() {return new Absyn.NotExpr(e);}
        | e = Prime() {return e;}
{
Absyn.Expr Prime() : 
{
	Token t; Absyn.Expr e; Absyn.Type type; LinkedList<Absyn.Expr> args = new LinkedList<Absyn.Expr>();
}
{
	t = <STRING> {return new Absyn.StringLiteral(t.toString());}
	| t = <INT> {return new Absyn.IntegerLiteral(Integer.parseInt(t.image));}
	| "null" {return new Absyn.NullExpr(); }
	| "new" type = BaseType() "[" e = Expression() "]" {return new Absyn.NewArrayExpr(type,e); } //format for arrays Basetype works with []
	| "Xinu" "." t = <ID>
        "(" [ arg = Expression() { args.add(arg); }
                ( "," arg = Expression()  { args.add(arg); } )* ]
        ")" { return new Absyn.XinuCallExpr(t.toString(), args); } //same as other xinu but no semi colon
	| t = <ID> {return new Absyn.IdentifierExpr(t.toString()); }
	| "(" e = Expression() ")" {return e;}
}


Absyn.Stmt IfState() : //checks format of if cond + statement + else
{
	Absyn.Expr condition;
	Absyn.Stmt then;
	Absyn.Stmt elseStmt = null;
}
{
	"if" "(" condition = Expression() ")" then = Statement()
	[ LOOKAHEAD(1) "else" elseStmt = Statement() ]
	{ return new Absyn.IfStmt(condition ,then,elseStmt); }
}

Absyn.Stmt WhileState(): //same as before simpiler 
{
	Absyn.Expr condition;
	Absyn.Stmt then;
}
{
	"while" "(" cond = Expression() ")" body = Statement() {return new Absyn.WhileStmt(cond, body); }
}
