/* Generated By:JavaCC: Do not edit this line. MiniJavaParserConstants.java */
package Parse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 33;
  /** RegularExpression Id. */
  int STRING = 34;
  /** RegularExpression Id. */
  int ID = 47;
  /** RegularExpression Id. */
  int LETTER = 48;
  /** RegularExpression Id. */
  int DIGIT = 49;
  /** RegularExpression Id. */
  int UNDER = 50;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"class\"",
    "\"public\"",
    "\"static\"",
    "\"if\"",
    "\"while\"",
    "\"true\"",
    "\"false\"",
    "\"void\"",
    "\"int\"",
    "\"boolean\"",
    "\".\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\"main\"",
    "\"String\"",
    "\"Thread\"",
    "\"Xinu\"",
    "\"new\"",
    "\"this\"",
    "\"null\"",
    "\"extends\"",
    "<INT>",
    "<STRING>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"!= \"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"?\"",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "\"_\"",
    "<token of kind 51>",
    "\"=\"",
    "\"!=\"",
  };

}
