/* MiniJavaParser.java */
/* Generated By:JavaCC: Do not edit this line. MiniJavaParser.java */
  package Parse;
  import java.util.LinkedList;
  public class MiniJavaParser implements MiniJavaParserConstants {

/********************/
/* MiniJava Grammar */
/********************/

// Goal 	::= 	MainClass ( ClassDeclaration | ThreadDeclaration )* <EOF>
  static final public Absyn.Program Goal() throws ParseException {LinkedList<Absyn.ClassDecl> cl = new LinkedList<Absyn.ClassDecl>();
    MainClassDeclaration(cl);
    jj_consume_token(0);
{if ("" != null) return new Absyn.Program(cl);}
    throw new Error("Missing return statement in function");
}

// MainClass 	::= 	"class" Identifier "{" "public" "static" "void" "main" "(" "String" "[" "]" Identifier ")" "{" Statement "}" "}"
  static final public Absyn.ClassDecl MainClassDeclaration(LinkedList<Absyn.ClassDecl> cl) throws ParseException {Absyn.ClassDecl  cd;
 Absyn.Stmt stmt;
 Absyn.VarDecl var;
 Token name, arg;
 LinkedList<Absyn.MethodDecl> methods = new LinkedList<Absyn.MethodDecl>();
 LinkedList<Absyn.Formal> formals     = new LinkedList<Absyn.Formal>();
 LinkedList<Absyn.VarDecl> locals     = new LinkedList<Absyn.VarDecl>();
 LinkedList<Absyn.Stmt> stmts         = new LinkedList<Absyn.Stmt>();
    jj_consume_token(6);
    name = jj_consume_token(ID);
    jj_consume_token(17);
    jj_consume_token(7);
    jj_consume_token(8);
    jj_consume_token(13);
    jj_consume_token(25);
    jj_consume_token(19);
    jj_consume_token(26);
    jj_consume_token(21);
    jj_consume_token(22);
    arg = jj_consume_token(ID);
    jj_consume_token(20);
formals.add(new Absyn.Formal(
   new Absyn.ArrayType(
    new Absyn.IdentifierType("String")),
     arg.toString()));
    jj_consume_token(17);
    label_1:
    while (true) {
      if (jj_2_1(2147483647)) {
        ;
      } else {
        break label_1;
      }
      var = VarDeclaration();
locals.add(var);
    }
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 28:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_2;
      }
      stmt = Statement();
stmts.add(stmt);
    }
    jj_consume_token(18);
    jj_consume_token(18);
methods.add(new Absyn.MethodDecl(null, false, "main", formals,
    locals, stmts, new Absyn.IntegerLiteral(0)));
  cd = new Absyn.ClassDecl(name.toString(),
      null,
      new LinkedList<Absyn.VarDecl>(), methods);
  cl.add(cd);
  {if ("" != null) return cd;}
    throw new Error("Missing return statement in function");
}

// VarDeclaration 	::= 	Type Identifier ( = Expression )? ";"
  static final public Absyn.VarDecl VarDeclaration() throws ParseException {Absyn.Type type = null;
 Token      name = null;
 Absyn.Expr init = null;
    type = Type();
    name = jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 52:{
      jj_consume_token(52);
      init = Expression();
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      ;
    }
    jj_consume_token(23);
{if ("" != null) return new Absyn.VarDecl(type, name.toString(), init);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Type Type() throws ParseException {Absyn.Type type;
    type = BaseType();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 21:{
        ;
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        break label_3;
      }
      jj_consume_token(21);
      jj_consume_token(22);
type = new Absyn.ArrayType(type);
    }
{if ("" != null) return type;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Type BaseType() throws ParseException {Token name;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 14:{
      jj_consume_token(14);
{if ("" != null) return new Absyn.IntegerType();}
      break;
      }
    case 15:{
      jj_consume_token(15);
{if ("" != null) return new Absyn.BooleanType();}
      break;
      }
    case ID:{
      name = jj_consume_token(ID);
{if ("" != null) return new Absyn.IdentifierType(name.toString());}
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Stmt Statement() throws ParseException {Absyn.Stmt stmt;
    stmt = XinuCallStatement();
{if ("" != null) return stmt;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.XinuCallStmt XinuCallStatement() throws ParseException {Token method;
 Absyn.Expr arg;
 LinkedList<Absyn.Expr> args = new LinkedList<Absyn.Expr>();
    jj_consume_token(28);
    jj_consume_token(16);
    method = jj_consume_token(ID);
    jj_consume_token(19);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 19:
    case INT:
    case STRING:{
      arg = Expression();
args.add(arg);
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 24:{
          ;
          break;
          }
        default:
          jj_la1[4] = jj_gen;
          break label_4;
        }
        jj_consume_token(24);
        arg = Expression();
args.add(arg);
      }
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    jj_consume_token(20);
    jj_consume_token(23);
{if ("" != null) return new Absyn.XinuCallStmt(method.toString(), args);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr Expression() throws ParseException {Absyn.Expr e;
    e = Or();
{if ("" != null) return e;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr Or() throws ParseException {Absyn.Expr left, right;
    left = And();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 44:{
        ;
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        break label_5;
      }
      jj_consume_token(44);
      right = And();
{if ("" != null) return new Absyn.OrExpr(left,right);}
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr And() throws ParseException {Absyn.Expr left, right;
    left = Equals();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 43:{
        ;
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        break label_6;
      }
      jj_consume_token(43);
      right = Equals();
{if ("" != null) return new Absyn.AndExpr(left,right);}
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr Equals() throws ParseException {Absyn.Expr left, right;
    left = Compare();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 41:{
        ;
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        break label_7;
      }
      jj_consume_token(41);
      right = Compare();
{if ("" != null) return new Absyn.EqualExpr(left,right);}
      jj_consume_token(53);
      right = Compare();
{if ("" != null) return new Absyn.NotEqExpr(left,right);}
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr Compare() throws ParseException {Absyn.Expr left, right;
    left = AddSub();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 40:{
        ;
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        break label_8;
      }
      jj_consume_token(40);
      right = AddSub();
{if ("" != null) return new Absyn.GreaterExpr(left,right);}
      jj_consume_token(39);
      right = AddSub();
{if ("" != null) return new Absyn.LesserExpr(left,right);}
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr AddSub() throws ParseException {Absyn.Expr left, right;
    left = MultDiv();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 35:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_9;
      }
      jj_consume_token(35);
      right = MultDiv();
{if ("" != null) return new Absyn.AddExpr(left,right);}
      jj_consume_token(36);
      right = MultDiv();
{if ("" != null) return new Absyn.SubExpr(left,right);}
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr MultDiv() throws ParseException {Absyn.Expr left, right;
    left = Prime();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 37:{
        ;
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        break label_10;
      }
      jj_consume_token(37);
      right = Prime();
{if ("" != null) return new Absyn.MulExpr(left,right);}
      jj_consume_token(38);
      right = Prime();
{if ("" != null) return new Absyn.DivExpr(left,right);}
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr Prime() throws ParseException {Token t; Absyn.Expr e;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STRING:{
      t = jj_consume_token(STRING);
{if ("" != null) return new Absyn.StringLiteral(t.toString());}
      break;
      }
    case INT:{
      t = jj_consume_token(INT);
{if ("" != null) return new Absyn.IntegerLiteral(Integer.parseInt(t.image));}
      break;
      }
    case 19:{
      jj_consume_token(19);
      e = Expression();
      jj_consume_token(20);
{if ("" != null) return e;}
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_3R_Compare_266_11_28()
 {
    if (jj_scan_token(40)) return true;
    if (jj_3R_AddSub_275_85_27()) return true;
    if (jj_scan_token(39)) return true;
    if (jj_3R_AddSub_275_85_27()) return true;
    return false;
  }

  static private boolean jj_3R_MultDiv_285_85_29()
 {
    if (jj_3R_Prime_301_2_31()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_MultDiv_286_11_32()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_Or_237_85_20()
 {
    if (jj_3R_And_246_85_21()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Or_238_4_22()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_VarDeclaration_178_2_11()
 {
    if (jj_3R_Type_187_2_12()) return true;
    if (jj_scan_token(ID)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_VarDeclaration_178_30_13()) jj_scanpos = xsp;
    if (jj_scan_token(23)) return true;
    return false;
  }

  static private boolean jj_3R_Equals_256_11_26()
 {
    if (jj_scan_token(41)) return true;
    if (jj_3R_Compare_265_85_25()) return true;
    if (jj_scan_token(53)) return true;
    if (jj_3R_Compare_265_85_25()) return true;
    return false;
  }

  static private boolean jj_3R_AddSub_275_85_27()
 {
    if (jj_3R_MultDiv_285_85_29()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_AddSub_276_11_30()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_VarDeclaration_178_2_11()) return true;
    return false;
  }

  static private boolean jj_3R_Prime_303_4_35()
 {
    if (jj_scan_token(19)) return true;
    if (jj_3R_Expression_230_9_16()) return true;
    if (jj_scan_token(20)) return true;
    return false;
  }

  static private boolean jj_3R_Prime_302_4_34()
 {
    if (jj_scan_token(INT)) return true;
    return false;
  }

  static private boolean jj_3R_And_247_12_24()
 {
    if (jj_scan_token(43)) return true;
    if (jj_3R_Equals_255_85_23()) return true;
    return false;
  }

  static private boolean jj_3R_Prime_301_2_33()
 {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  static private boolean jj_3R_Prime_301_2_31()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Prime_301_2_33()) {
    jj_scanpos = xsp;
    if (jj_3R_Prime_302_4_34()) {
    jj_scanpos = xsp;
    if (jj_3R_Prime_303_4_35()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_Compare_265_85_25()
 {
    if (jj_3R_AddSub_275_85_27()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Compare_266_11_28()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_VarDeclaration_178_30_13()
 {
    if (jj_scan_token(52)) return true;
    if (jj_3R_Expression_230_9_16()) return true;
    return false;
  }

  static private boolean jj_3R_MultDiv_286_11_32()
 {
    if (jj_scan_token(37)) return true;
    if (jj_3R_Prime_301_2_31()) return true;
    if (jj_scan_token(38)) return true;
    if (jj_3R_Prime_301_2_31()) return true;
    return false;
  }

  static private boolean jj_3R_BaseType_199_4_19()
 {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3R_BaseType_198_4_18()
 {
    if (jj_scan_token(15)) return true;
    return false;
  }

  static private boolean jj_3R_BaseType_197_4_17()
 {
    if (jj_scan_token(14)) return true;
    return false;
  }

  static private boolean jj_3R_BaseType_197_4_14()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_BaseType_197_4_17()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseType_198_4_18()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseType_199_4_19()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_Equals_255_85_23()
 {
    if (jj_3R_Compare_265_85_25()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Equals_256_11_26()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_Or_238_4_22()
 {
    if (jj_scan_token(44)) return true;
    if (jj_3R_And_246_85_21()) return true;
    return false;
  }

  static private boolean jj_3R_AddSub_276_11_30()
 {
    if (jj_scan_token(35)) return true;
    if (jj_3R_MultDiv_285_85_29()) return true;
    if (jj_scan_token(36)) return true;
    if (jj_3R_MultDiv_285_85_29()) return true;
    return false;
  }

  static private boolean jj_3R_Type_188_4_15()
 {
    if (jj_scan_token(21)) return true;
    if (jj_scan_token(22)) return true;
    return false;
  }

  static private boolean jj_3R_Expression_230_9_16()
 {
    if (jj_3R_Or_237_85_20()) return true;
    return false;
  }

  static private boolean jj_3R_And_246_85_21()
 {
    if (jj_3R_Equals_255_85_23()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_And_247_12_24()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_Type_187_2_12()
 {
    if (jj_3R_BaseType_197_4_14()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Type_188_4_15()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public MiniJavaParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[13];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x10000000,0x0,0x200000,0xc000,0x1000000,0x80000,0x0,0x0,0x0,0x0,0x0,0x0,0x80000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x100000,0x0,0x8000,0x0,0x6,0x1000,0x800,0x200,0x100,0x8,0x20,0x6,};
	}
  static final private JJCalls[] jj_2_rtns = new JJCalls[1];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MiniJavaParser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MiniJavaParser(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 13; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 13; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MiniJavaParser(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 13; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 13; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MiniJavaParser(MiniJavaParserTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 13; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MiniJavaParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 13; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[54];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 13; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 54; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 1; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

                               }
